language: node_js
node_js:
- '0.10'
before_script:
- sudo apt-get install duplicity
- sudo npm install mocha -g
before_deploy:
- npm install json
- node_modules/.bin/json -E "this.version='$TRAVIS_TAG'" -f package.json -I
script: npm test
deploy:
  provider: npm
  email: JanS@DracoBlue.de
  api_key:
    secure: HLzzmX+TWBy3JjKmRpF9G+ZPQtFFtD8ptX2wkKQigD3PjA1vYhqGfkLyQyFblH14thfQWXnMJwbomoyh85humN4qSjSyVEFEfDMCcWLhTFPmoJvuIytpDr9SCiaBnUbtDmS5z4M6uVX/cKTDU49F6atKCx1+bWdZVI+AZVmkA7A=
  on:
    tags: true
    repo: DracoBlue/node-duplicity
    all_branches: true
